gantsign/ansible-role-intellij

- README.md
- defaults/main.yml
Changed default for `intellij_download_dir` from `/tmp/ansible/data` to `~/.ansible/tmp/downloads`.
Enhancement: resolves #8
> Moved default intellij_download_dir under user home

- templates/facts.j2
It was unnecessarily verbose.
Enhancement: resolves #12
> Removed "intellij_" prefix from IntelliJ facts

- README.md
- defaults/main.yml
Changed to match fact in version `3.0.0` of `gantsign.maven`.
Enhancement: resolves #15
> Updated default value for maven_home

- README.md
- defaults/main.yml
Changed to match fact in version `2.0.0` of `gantsign.java`.
Enhancement: resolves #16
> Updated default value for java_home

- templates/facts.j2
- templates/jetbrains-idea.desktop.j2
This is useful to tell users that a file has been placed by Ansible and manual changes are likely to be overwritten.
> Added ansible_managed header to template files

- README.md
For consistency the titles needed to be in titlecase like the others.
> Fixed case of titles in README.md

- README.md
- templates/facts.j2
To configure the Unity launcher you need the name of the desktop file rather than the absolute path.
Enhancement: resolves #29
> Added desktop_filename fact

- .editorconfig
- templates/.editorconfig
Mainly to catch trailing whitespace and set default indent levels.
> Added .editorconfig files

- tasks/main.yml
Using tar to maintain support for Ansible 1.9 while using `--strip-components`.
> Suppress warning about using tar

- README.md
The intellij-java-google-style.xml formatting doesn't match google-java-format so it's misleading to users to suggest using them both at the same time.
> Change README.md to install Checkstyle

- tasks/configure-disabled-plugins.yml
- tasks/configure-jdk-table.yml
- tasks/configure-project-defaults.yml
Previously the path for the users home directory was hardcoded, now it is determined dynamically.
> Fixed user home path

- defaults/main.yml
Was using the home directory of the local user rather than the remote user.
> Fixed intellij_download_dir path

- templates/install-intellij-plugins.sh.j2
- tests/test.yml
- tests/test_role.py
Plugin IDs containing whitespace now install correctly.
Enhancement: resolves #55
> Fixed plugin ID whitespace

- tasks/install-plugins.yml
Idempotence shouldn't fail if you use the role multiple times to install different plugins.
> Plugin script shouldn't be regarded as a change

- templates/install-intellij-plugins.sh.j2
- tests/test.yml
- tests/test_role.py
The `chown` command was failing because it was treating file names with spaces as multiple files.
> Fixed for plugins with spaces in file names

- tests/test_role.py
It was hardcoded for the plugin tests.
> Made config dir in tests dynamic

- templates/install-intellij-plugins.sh.j2
New features:
* Prints message when plugin is not found
* Up to 2 auto-retries if there is a HTTP failure
* Prints message when there's a fatal HTTP failure
> Handle HTTP errors when installing plugins

- README.md
- defaults/main.yml
- tasks/configure-code-style.yml
- tasks/configure-disabled-plugins.yml
- tasks/configure-jdk-table.yml
- tasks/configure-project-defaults.yml
- tasks/install-code-styles.yml
- tasks/install-plugins.yml
- tasks/install.yml
- vars/editions/community.yml
- vars/editions/ultimate.yml
- vars/main.yml
Switched to single quotes (rather than double quotes) for YAML strings where escaping isn't required.
> Switched to single quotes for YAML strings

- README.md
- defaults/main.yml
It's best to stick with the built in JDK anyway as it has customizations from JetBrains to work better with IntelliJ.
> Removed intellij_jdk_home as it wasn't used

- README.md
- defaults/main.yml
It's replaced by `users.intellij_jdks` and `users.intellij_default_jdk`, which allow multiple JDK versions to be configured.
> Deprecated intellij_default_jdk_home

- templates/install-intellij-plugins.sh.j2
Some non-JetBrains plugins have a different URL format; this change fixes support for plugins that don't follow the JetBrains plugin URL format.
Bug fix: resolves #94
> Fixed support for non-JetBrains plugins

- templates/install-intellij-plugins.sh.j2
- tests/test.yml
- tests/test_role.py
If a plugin is distributed as a JAR rather than a ZIP file it should not be unpacked.
Bug fix: resolves #98
> Fixed support for plugins distributed as JARs

- README.md
- tasks/configure-license.yml
- tasks/configure.yml
If you're using IntelliJ IDEA Ultimate Edition you can now configure this role to install your license key.
> Added support for Ultimate Edition license keys

- templates/install-intellij-plugins.sh.j2
It seems JetBrains have moved the plugin hosting to S3 and now there's an additional redirect that needs to be followed.
> Fixed plugin downloads

- templates/install-intellij-plugins.sh.j2
The test for the file name patten wasn't implemented correctly.
> Fixed file names of downloaded plugins

- templates/install-intellij-plugins.sh.j2
JetBrains have added a query string to the plugin downloads, which had broken the detection for JAR packaged plugins (these plugins must not be extracted).
Also, stripped the query string from the file name of downloaded plugins.
> Fixed JAR packaged plugins install

- tasks/install.yml
Previously, intellij was being downloaded regardless of whether it was
installed already or not. This checks whether the intellij bin directory
exists already, and skips the download if so. This is the same logic
used by the tar command in the 'install IntelliJ IDEA' task.
> Only download intellij when it isn't installed

- tasks/install-plugins.yml
Installing packages requires root privileges
> Use 'become' when installing plugin dependencies

- tests/test.yml
- tests/test_role.py
Updates have almost stopped since the official Go plugin was released.
> Remove Go plugin from tests

- molecule/centos/playbook.yml
- molecule/default/playbook.yml
- molecule/default/tests/test_role.py
- molecule/python3/playbook.yml
- molecule/ultimate/playbook.yml
It's now available for IntelliJ 2018.1.
> Restored test for Google Format plugin

- tasks/install.yml
Because of the need to strip the top level directory we were using `tar` directly. Now we've increased the minimum Ansible version to 2.3, we can use the `extra_opts` option of the `unarchive` module instead.
> Changed from tar command to unarchive module

- tasks/install-code-styles.yml
Now Ansible 2.3 is the minimum version for this role we can use `remote_src` of the copy module.
> Use copy module to install code styles

- molecule/python3/playbook.yml
AdoptOpenJDK isn't serving up `jdk-10+23` any more.
> Fixed JDK 10 test

- README.md
- molecule/centos/playbook.yml
- molecule/default/playbook.yml
- molecule/python3/playbook.yml
- molecule/ultimate/playbook.yml
- tasks/configure-code-style.yml
- templates/code.style.schemes.j2
- templates/code.style.schemes.xml.j2
Renamed `intellij_active_codestyle` to `intellij_default_codestyle`; it's more accurate and more consistent with the JDK property.
> Renamed intellij_active_codestyle

- tasks/configure.yml
- tasks/main.yml
Since Ansible 2.4 `include` has been deprecated.
```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
```
> Resolved deprecation warning for include

- meta/main.yml
Needed since Ansible Galaxy 3 to have a role name different to the repo name.
> Added role_name to the Ansible Galaxy metadata

- molecule/centos/tests/test_role.py
- molecule/default/tests/test_role.py
- molecule/minimal/tests/test_role.py
Other fixtures are deprecated and will be removed in 2.0 Testinfra release.
> Changed tests to use host fixture

- molecule/default/playbook.yml
- molecule/python3/playbook.yml
- molecule/ultimate/playbook.yml
The API isn't working with named releases.
> Workaround bug in AdoptOpenJDK API

- molecule/default/playbook.yml
- molecule/python3/playbook.yml
- molecule/ultimate/playbook.yml
It appears Ubuntu changed their packaging for the JDK and have introduced a separate headless option.
> Changed to test with the headless JDK

- README.md
- library/intellij_configure_jdk.py
- molecule/centos/playbook.yml
- molecule/centos/tests/test_role.py
Installing the JDK by itself often isn't enough.
Fix: resolves #220
> Improve messages about invalid JDKs

- README.md
- meta/main.yml
Canonical have ended standard support for Ubuntu Trusty (14.04).
> Dropped support for Ubuntu Trusty

- molecule/default/playbook.yml
- molecule/default/tests/test_role.py
- molecule/python3/playbook.yml
- molecule/ultimate/playbook.yml
It appears Java 11.0.0 is no longer available from AdoptOpenJDK.
> Updated tests to use Java 11.0.6

- molecule/default/playbook.yml
- molecule/python3/playbook.yml
- molecule/ultimate/playbook.yml
> Switched to AdoptOpenJDK V3 API for testing

- tasks/install.yml
```
[DEPRECATION WARNING]: The parameter "sha256sum" has been deprecated and will
be removed, use "checksum" instead. This feature will be removed from ansible-
base in version 2.14. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```
> Fixed get_url.sha256sum deprecation warning

- .github/workflows/ci.yml
To reduce the chance of hitting Docker Hub download limits.
> Configured CI to login to Docker Hub

- library/intellij_install_plugin.py
- molecule/centos/converge.yml
- molecule/centos/tests/test_role.py
- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/opensuse/converge.yml
- molecule/opensuse/tests/test_role.py
- molecule/ultimate/converge.yml
The install was failing to set the ownership unless the directory is an entry in the zip file.
> Fixed install for plugins with missing dirs in zip

- README.md
- defaults/main.yml
- vars/versions/2021.1.2-community.yml
- vars/versions/2021.1.2-ultimate.yml
2021.1.2 is now the default version installed.
> Updated to IntelliJ version 2021.1.2

- README.md
- defaults/main.yml
- vars/versions/2021.2.2-community.yml
- vars/versions/2021.2.2-ultimate.yml
2021.2.2 is now the default version installed.
> Updated to IntelliJ version 2021.2.2

- README.md
- defaults/main.yml
- vars/versions/2021.3.2-community.yml
- vars/versions/2021.3.2-ultimate.yml
2021.3.2 is now the default version installed.
> Updated to IntelliJ version 2021.3.2

- README.md
- defaults/main.yml
- vars/versions/2022.1.1-community.yml
- vars/versions/2022.1.1-ultimate.yml
2022.1 is now the default version installed.
> Updated to IntelliJ version 2022.1

- README.md
- defaults/main.yml
- vars/versions/2022.1.3-community.yml
- vars/versions/2022.1.3-ultimate.yml
2022.1.3 is now the default version installed.
> Updated to IntelliJ version 2022.1.3

- README.md
- defaults/main.yml
- vars/versions/2022.1.4-community.yml
- vars/versions/2022.1.4-ultimate.yml
2022.1.4 is now the default version installed.
> Updated to IntelliJ version 2022.1.4

- README.md
- defaults/main.yml
- vars/versions/2022.2-community.yml
- vars/versions/2022.2-ultimate.yml
2022.2 is now the default version installed.
> Updated to IntelliJ version 2022.2

- README.md
- defaults/main.yml
- vars/versions/2022.2.1-community.yml
- vars/versions/2022.2.1-ultimate.yml
2022.2.1 is now the default version installed.
> Updated to IntelliJ version 2022.2.1

- README.md
- defaults/main.yml
- vars/versions/2022.2.2-community.yml
- vars/versions/2022.2.2-ultimate.yml
2022.2.2 is now the default version installed.
> Updated to IntelliJ version 2022.2.2

- README.md
- defaults/main.yml
- vars/versions/2022.3.2-community.yml
- vars/versions/2022.3.2-ultimate.yml
2022.3.2 is now the default version installed.
> Updated to IntelliJ version 2022.3.2

- README.md
- defaults/main.yml
- vars/versions/2022.3.3-community.yml
- vars/versions/2022.3.3-ultimate.yml
2022.3.3 is now the default version installed.
> Updated to IntelliJ version 2022.3.3

- molecule/default/converge.yml
- molecule/default/tests/test_role.py
- molecule/opensuse/converge.yml
- molecule/opensuse/tests/test_role.py
- molecule/rocky/converge.yml
- molecule/rocky/tests/test_role.py
- molecule/ultimate/converge.yml
`com.dubreuia` is deprecated, moved to `software.xdev.saveactions` fork.
> Migrated to new Save Actions Plugin

- README.md
- meta/main.yml
- molecule/ultimate/molecule.yml
Canonical have ended standard support for Ubuntu Bionic.
> Dropped support for Ubuntu Bionic

- README.md
- meta/main.yml
- molecule/ultimate/molecule.yml
Canonical have ended standard support for Ubuntu Focal.
> Dropped support for Ubuntu Focal
