gantsign/ansible-role-intellij

README.md
defaults/main.yml
vars/versions/2016.2.2-community.yml
vars/versions/2016.2.2-ultimate.yml

2016.2.2 is now the default version installed.
Enhancement: resolved #1

Updated to IntelliJ version 2016.2.2

---

.gitignore
.travis.yml
README.md
ansible.cfg
molecule.yml
tasks/main.yml
tests/inventory
tests/requirements.yml
tests/test.yml
tests/test_role.py

Makes it easy to test locally during development.
Enhancement: resolves #3

Switched to use Molecule to test role

---

README.md
defaults/main.yml
vars/versions/2016.2.3-community.yml
vars/versions/2016.2.3-ultimate.yml

2016.2.3 is now the default version installed.

Updated to IntelliJ version 2016.2.3

---

README.md

More info on what's required and what's optional.

Improved user specific docs in README.md

---

README.md
tasks/configure-code-style.yml
tasks/install-code-styles.yml
tasks/main.yml
templates/.editorconfig
templates/code.style.schemes.j2
templates/code.style.schemes.xml.j2
tests/test.yml
tests/test_role.py

Important for code consistency and version control.
Enhancement: resolves #38

Added install and configure code styles

---

tasks/configure-disabled-plugins.yml
tests/test.yml

Disabled plugins task will now correctly handle None.

Improved handling of None

---

README.md
defaults/main.yml
vars/versions/2016.2.4-community.yml
vars/versions/2016.2.4-ultimate.yml

2016.2.4 is now the default version installed.

Updated to IntelliJ version 2016.2.4

---

tasks/configure.yml
tasks/main.yml

More robust handling when no users are specified.

Improve handling of optional configuration

---

README.md
tasks/configure.yml
tasks/install-plugins.yml
templates/install-intellij-plugins.sh.j2
tests/test.yml
tests/test_role.py
vars/main.yml

Install optional plugins during provisioning.
Enhancement: resolves #44

Added ability to install plugins

---

.travis.yml
README.md
meta/main.yml
tasks/install.yml

Ansible 2 is now the minimum version.

Corrected minimum Ansible version

---

README.md
defaults/main.yml
tasks/install.yml

Improved support for proxy users.
Enhancement: resolves #58

Increased timeout for IntelliJ download

---

README.md
defaults/main.yml
vars/versions/2016.2.5-community.yml
vars/versions/2016.2.5-ultimate.yml

2016.2.5 is now the default version installed.

Updated to IntelliJ version 2016.2.5

---

README.md
templates/facts.j2

To support other roles that perform user specific config.

Added user_dirname Ansible fact

---

templates/install-intellij-plugins.sh.j2

The Ultimate Edition has a different filename for the application config.

Fixed plugin install on Ultimate Edition

---

molecule.yml
tests/test_role.py

Both the Community Edition and Ultimate Edition will now be tested.

Added Ultimate Edition to tests

---

README.md
defaults/main.yml
vars/versions/2016.3-community.yml
vars/versions/2016.3-ultimate.yml

2016.3 is now the default version installed.

Updated to IntelliJ version 2016.3

---

README.md
meta/main.yml
molecule.yml
tasks/configure-jdk-table.yml
tasks/configure.yml
tasks/install-plugins.yml
templates/install-intellij-plugins.sh.j2
tests/test.yml
tests/test_role.py
vars/main.yml

Switched to Ansible `package` module for installing dependencies.
Enhancement: resolves #70
Enhancement: resolves #71

Added support for CentOS 7

---

tasks/install-plugins.yml
tasks/main.yml

Moved check if users are specified up to the top.

Simplified user configuration conditions

---

README.md
tasks/configure-project-defaults.yml

You can now perform a dry run of this role by running Ansible with `--check`.

Added support for check mode

---

README.md
defaults/main.yml
vars/versions/2016.3.1-community.yml
vars/versions/2016.3.1-ultimate.yml

2016.3.1 is now the default version installed.

Updated to IntelliJ version 2016.3.1

---

README.md
defaults/main.yml
vars/versions/2016.3.2-community.yml
vars/versions/2016.3.2-ultimate.yml

2016.3.2 is now the default version installed.

Updated to IntelliJ version 2016.3.2

---

README.md
defaults/main.yml
vars/versions/2016.3.3-community.yml
vars/versions/2016.3.3-ultimate.yml

2016.3.3 is now the default version installed.

Updated to IntelliJ version 2016.3.3

---

README.md
defaults/main.yml
vars/versions/2016.3.4-community.yml
vars/versions/2016.3.4-ultimate.yml

2016.3.4 is now the default version installed.

Updated to IntelliJ version 2016.3.4

---

README.md
defaults/main.yml
vars/versions/2016.3.5-community.yml
vars/versions/2016.3.5-ultimate.yml

2016.3.5 is now the default version installed.

Updated to IntelliJ version 2016.3.5

---

README.md
defaults/main.yml
templates/install-intellij-plugins.sh.j2
vars/versions/2017.1-community.yml
vars/versions/2017.1-ultimate.yml

2017.1 is now the default version installed.

Updated to IntelliJ version 2017.1

---

.travis.yml

Pinned Ansible to 2.2.1 until https://github.com/ansible/ansible/issues/23016 is resolved.

Added workaround for Ansible issue 23016

---

README.md
defaults/main.yml
templates/install-intellij-plugins.sh.j2

Useful for local mirrors / adding additional URL parameters.
Enhancement: resolves #93

Made plugin manager URL configurable

---

README.md
defaults/main.yml
vars/versions/2017.1.1-community.yml
vars/versions/2017.1.1-ultimate.yml

2017.1.1 is now the default version installed.

Updated to IntelliJ version 2017.1.1

---

README.md
defaults/main.yml
vars/versions/2017.1.2-community.yml
vars/versions/2017.1.2-ultimate.yml

2017.1.2 is now the default version installed.

Updated to IntelliJ version 2017.1.2

---

README.md
defaults/main.yml
vars/versions/2017.1.3-community.yml
vars/versions/2017.1.3-ultimate.yml

2017.1.3 is now the default version installed.

Updated to IntelliJ version 2017.1.3

---

README.md
defaults/main.yml
vars/versions/2017.1.4-community.yml
vars/versions/2017.1.4-ultimate.yml

2017.1.4 is now the default version installed.

Updated to IntelliJ version 2017.1.4

---

tasks/install.yml

Fixed task name case

---

README.md
defaults/main.yml
vars/versions/2017.1.5-community.yml
vars/versions/2017.1.5-ultimate.yml

2017.1.5 is now the default version installed.

Updated to IntelliJ version 2017.1.5

---

README.md
defaults/main.yml
vars/versions/2017.2-community.yml
vars/versions/2017.2-ultimate.yml

2017.2 is now the default version installed.

Updated to IntelliJ version 2017.2

---

README.md
defaults/main.yml
vars/versions/2017.2.1-community.yml
vars/versions/2017.2.1-ultimate.yml

2017.2.1 is now the default version installed.

Updated to IntelliJ version 2017.2.1

---

README.md
defaults/main.yml
vars/versions/2017.2.2-community.yml
vars/versions/2017.2.2-ultimate.yml

2017.2.2 is now the default version installed.

Updated to IntelliJ version 2017.2.2

---

README.md
defaults/main.yml
tests/test_role.py
vars/versions/2017.2.3-community.yml
vars/versions/2017.2.3-ultimate.yml

2017.2.3 is now the default version installed.

Updated to IntelliJ version 2017.2.3

---

README.md
meta/main.yml
molecule.yml
tests/test.yml

Its end of life was over a year ago.

Dropped support for Ubuntu Wily Werewolf

---

README.md
defaults/main.yml
vars/versions/2017.2.4-community.yml
vars/versions/2017.2.4-ultimate.yml

2017.2.4 is now the default version installed.

Updated to IntelliJ version 2017.2.4

---

templates/jdk-1.9-oracle.xsl

JDK 9 will be released this week.

Updated config for Oracle JDK 9

---

tasks/configure-jdk-table.yml
templates/jdk-9-openjdk.xsl
templates/jdk-9-oracle.xsl

You can now configure a Java 9 JDK as an SDK.

Added support for Java 9 JDK

---

README.md
defaults/main.yml
vars/versions/2017.2.5-community.yml
vars/versions/2017.2.5-ultimate.yml

2017.2.5 is now the default version installed.

Updated to IntelliJ version 2017.2.5

---

README.md
defaults/main.yml
vars/versions/2017.2.6-community.yml
vars/versions/2017.2.6-ultimate.yml

2017.2.6 is now the default version installed.

Updated to IntelliJ version 2017.2.6

---

README.md
meta/main.yml
tasks/configure-project-defaults.yml

Increased minimum Ansible version to 2.3

---

README.md
defaults/main.yml
vars/versions/2017.3-community.yml
vars/versions/2017.3-ultimate.yml

2017.3 is now the default version installed.

Updated to IntelliJ version 2017.3

---

README.md
defaults/main.yml
vars/versions/2017.3.1-community.yml
vars/versions/2017.3.1-ultimate.yml

2017.3.1 is now the default version installed.

Updated to IntelliJ version 2017.3.1

---

README.md
defaults/main.yml
vars/versions/2017.3.2-community.yml
vars/versions/2017.3.2-ultimate.yml

2017.3.2 is now the default version installed.

Updated to IntelliJ version 2017.3.2

---

README.md
defaults/main.yml
vars/versions/2017.3.3-community.yml
vars/versions/2017.3.3-ultimate.yml

2017.3.3 is now the default version installed.

Updated to IntelliJ version 2017.3.3

---

README.md
defaults/main.yml
vars/versions/2017.3.4-community.yml
vars/versions/2017.3.4-ultimate.yml

2017.3.4 is now the default version installed.

Updated to IntelliJ version 2017.3.4

---

README.md
defaults/main.yml
vars/versions/2017.3.5-community.yml
vars/versions/2017.3.5-ultimate.yml

2017.3.5 is now the default version installed.

Updated to IntelliJ version 2017.3.5

---

README.md
defaults/main.yml
molecule/centos/playbook.yml
molecule/default/playbook.yml
molecule/default/tests/test_role.py
molecule/ultimate/playbook.yml
vars/versions/2018.1-community.yml
vars/versions/2018.1-ultimate.yml

2018.1 is now the default version installed.

Updated to IntelliJ version 2018.1

---

tasks/configure-jdk-table.yml
templates/jdk-10-openjdk.xsl
templates/jdk-10-oracle.xsl

Added support for Java 10 SDKs

---

README.md
defaults/main.yml
vars/versions/2018.1.1-community.yml
vars/versions/2018.1.1-ultimate.yml

2018.1.1 is now the default version installed.

Updated to IntelliJ version 2018.1.1

---

README.md
defaults/main.yml
molecule/centos/playbook.yml
molecule/default/playbook.yml
molecule/ultimate/playbook.yml
tasks/configure-jdk-table.yml
tasks/configure-project-defaults.yml
tasks/install.yml

Replaced with `intellij_default_jdk` under users.

Dropped intellij_default_jdk_home configuration var

---

.travis.yml
molecule/centos/Dockerfile.j2
molecule/default/Dockerfile.j2
molecule/default/create.yml
molecule/default/destroy.yml
molecule/ultimate/Dockerfile.j2

Keeping up with the latest changes.

Updated Molecule to 2.12.1

---

.travis.yml

Was previously building the default scenario.

Run Molecule create & destroy with scenario

---

molecule/centos/molecule.yml
molecule/ultimate/molecule.yml

Added missing Molecule prepare steps

---

.travis.yml
molecule/default/tests/test_role.py
molecule/python3/Dockerfile.j2
molecule/python3/INSTALL.rst
molecule/python3/molecule.yml
molecule/python3/playbook.yml

In preparation for adding custom modules.

Added test for Python 3

---

library/intellij_set_default_jdk.py
molecule/centos/playbook.yml
molecule/default/playbook.yml
molecule/ultimate/playbook.yml
tasks/configure-project-defaults.yml
tasks/main.yml
templates/project.default.xml.j2

Made default JDK optional

---

.travis.yml
molecule/minimal/Dockerfile.j2
molecule/minimal/INSTALL.rst
molecule/minimal/molecule.yml
molecule/minimal/playbook.yml
molecule/minimal/tests/test_role.py
templates/install-intellij-plugins.sh.j2

The idempotency check was failing if none of the users install any plugins (it was always reporting as changed).

Fixed idempotency with no plugins

---

templates/facts.j2
templates/jetbrains-idea.desktop.j2

Allow for a more verbose ansible_managed message.

Added support for multiline ansible_managed

---

library/intellij_set_default_jdk.py

"specification" was misspelled.

Fixed typo in error message

---

library/intellij_set_default_jdk.py
library/intellij_set_default_maven.py

Better handling of whitespace.

Improved pretty printing of XML config

---

library/intellij_set_default_jdk.py

The `languageLevel` was set wrong.

Fixed setting default JDK

---

README.md
defaults/main.yml
vars/versions/2018.1.2-community.yml
vars/versions/2018.1.2-ultimate.yml

2018.1.2 is now the default version installed.

Updated to IntelliJ version 2018.1.2

---

README.md

To encourage use of the plugin install feature.

Documented procedure for querying plugin IDs

---

README.md
defaults/main.yml
vars/versions/2018.1.3-community.yml
vars/versions/2018.1.3-ultimate.yml

2018.1.3 is now the default version installed.

Updated to IntelliJ version 2018.1.3

---

.travis.yml

Keeping up with the latest changes.

Updated Molecule to 2.13.1

---

.travis.yml
library/intellij_configure_jdk.py
library/intellij_install_plugin.py
library/intellij_set_default_maven.py
molecule/python3/molecule.yml
tasks/configure.yml
vars/main.yml

Previous Python 3 tests weren't fully running Python 3.
Bug fix: resolves #163

Fixed role so it now works on Python 3

---

library/intellij_configure_jdk.py
library/intellij_install_plugin.py
library/intellij_set_default_jdk.py
library/intellij_set_default_maven.py

`yapf --style=google --in-place library/*.py`

Reformatted code

---

library/intellij_configure_jdk.py
library/intellij_install_plugin.py
library/intellij_set_default_jdk.py
library/intellij_set_default_maven.py

I'd gone a bit overboard converting strings to bytes for file related APIs, much of it wasn't necessary and has been removed.

Simplified Python 3 compatibility code

---

README.md
library/intellij_set_default_inspection_profile.py
molecule/centos/playbook.yml
molecule/default/playbook.yml
molecule/default/tests/test_role.py
molecule/python3/playbook.yml
molecule/ultimate/playbook.yml
tasks/configure-inspection-profiles.yml
tasks/configure.yml
tasks/install-code-styles.yml
tasks/install-inspection-profiles.yml
templates/editor.codeinsight.xml.j2

To encourage better code quality.

Added support for inspection profiles

---

README.md
defaults/main.yml
vars/versions/2018.1.4-community.yml
vars/versions/2018.1.4-ultimate.yml

2018.1.4 is now the default version installed.

Updated to IntelliJ version 2018.1.4

---

README.md
defaults/main.yml
vars/versions/2018.1.5-community.yml
vars/versions/2018.1.5-ultimate.yml

2018.1.5 is now the default version installed.

Updated to IntelliJ version 2018.1.5

---

README.md
defaults/main.yml
vars/versions/2018.1.6-community.yml
vars/versions/2018.1.6-ultimate.yml

2018.1.6 is now the default version installed.

Updated to IntelliJ version 2018.1.6

---

README.md
defaults/main.yml
vars/versions/2018.2-community.yml
vars/versions/2018.2-ultimate.yml

2018.2 is now the default version installed.

Updated to IntelliJ version 2018.2

---

.travis.yml
molecule/centos/molecule.yml
molecule/centos/tests/test_role.py
molecule/default/playbook.yml
molecule/python3/playbook.yml
molecule/ultimate/playbook.yml

Ensure this role works with Ansible 2.6.

Increased upper Ansible test range to Ansible 2.6

---

README.md
defaults/main.yml
vars/versions/2018.2.1-community.yml
vars/versions/2018.2.1-ultimate.yml

2018.2.1 is now the default version installed.

Updated to IntelliJ version 2018.2.1

---

README.md
defaults/main.yml
vars/versions/2018.2.2-community.yml
vars/versions/2018.2.2-ultimate.yml

2018.2.2 is now the default version installed.

Updated to IntelliJ version 2018.2.2

---

README.md

For users who want to conditionally install plugins.

Added link to companion role

---

molecule/python3/molecule.yml
molecule/ultimate/molecule.yml

Removed unnecessary trailing slash.

Fixed location of Molecule tests

---

README.md
defaults/main.yml
vars/versions/2018.2.3-community.yml
vars/versions/2018.2.3-ultimate.yml

2018.2.3 is now the default version installed.

Updated to IntelliJ version 2018.2.3

---

README.md
meta/main.yml
molecule/default/molecule.yml
molecule/minimal/molecule.yml
molecule/python3/molecule.yml

The latests LTS release of Ubuntu.

Added support for Ubuntu Bionic

---

README.md
defaults/main.yml
vars/versions/2018.2.4-community.yml
vars/versions/2018.2.4-ultimate.yml

2018.2.4 is now the default version installed.

Updated to IntelliJ version 2018.2.4

---

tasks/install-inspection-profiles.yml

Previously only updated if file name changed.

Changed to overwrite inspection profiles if URL changes

---

tasks/install-code-styles.yml

Previously only updated if file name changed.

Changed to overwrite code styles if URL changes

---

tasks/install.yml
vars/os-families/Debian.yml
vars/os-families/RedHat.yml
vars/os-families/Suse.yml
vars/os-families/default.yml

Added libcanberra-gtk-module dependency

---

library/intellij_set_default_jdk.py

Fixed default JDK without default Maven

---

library/intellij_set_default_jdk.py

Was failing because `jrunscript` now outputs `Warning: Nashorn engine is planned to be removed from a future JDK release`.

Fixed support for Java 11

---

README.md
defaults/main.yml
vars/versions/2018.2.5-community.yml
vars/versions/2018.2.5-ultimate.yml

2018.2.5 is now the default version installed.

Updated to IntelliJ version 2018.2.5

---

molecule/default/playbook.yml
molecule/default/tests/test_role.py
molecule/python3/playbook.yml
molecule/ultimate/playbook.yml

Java 10 is no longer supported.

Increased upper Java test version to 11

---

README.md
defaults/main.yml
vars/versions/2018.3-community.yml
vars/versions/2018.3-ultimate.yml

2018.3 is now the default version installed.

Updated to IntelliJ version 2018.3

---

README.md
defaults/main.yml
vars/versions/2018.3.1-community.yml
vars/versions/2018.3.1-ultimate.yml

2018.3.1 is now the default version installed.

Updated to IntelliJ version 2018.3.1

---

README.md
defaults/main.yml
vars/versions/2018.3.2-community.yml
vars/versions/2018.3.2-ultimate.yml

2018.3.2 is now the default version installed.

Updated to IntelliJ version 2018.3.2

---

README.md
defaults/main.yml
vars/versions/2018.3.3-community.yml
vars/versions/2018.3.3-ultimate.yml

2018.3.3 is now the default version installed.

Updated to IntelliJ version 2018.3.3

---

README.md
defaults/main.yml
vars/versions/2018.3.4-community.yml
vars/versions/2018.3.4-ultimate.yml

2018.3.4 is now the default version installed.

Updated to IntelliJ version 2018.3.4

---

README.md
defaults/main.yml
vars/versions/2018.3.5-community.yml
vars/versions/2018.3.5-ultimate.yml

2018.3.5 is now the default version installed.

Updated to IntelliJ version 2018.3.5

---

README.md
defaults/main.yml
vars/versions/2018.3.6-community.yml
vars/versions/2018.3.6-ultimate.yml

2018.3.6 is now the default version installed.

Updated to IntelliJ version 2018.3.6

---

README.md
defaults/main.yml
vars/versions/2019.1-community.yml
vars/versions/2019.1-ultimate.yml

2019.1 is now the default version installed.

Updated to IntelliJ version 2019.1

---

README.md
defaults/main.yml
vars/versions/2019.1.1-community.yml
vars/versions/2019.1.1-ultimate.yml

2019.1.1 is now the default version installed.

Updated to IntelliJ version 2019.1.1

---

README.md
defaults/main.yml
vars/versions/2019.1.2-community.yml
vars/versions/2019.1.2-ultimate.yml

2019.1.2 is now the default version installed.

Updated to IntelliJ version 2019.1.2

---

README.md
defaults/main.yml
vars/versions/2019.1.3-community.yml
vars/versions/2019.1.3-ultimate.yml

2019.1.3 is now the default version installed.

Updated to IntelliJ version 2019.1.3

---

README.md
defaults/main.yml
vars/versions/2019.2-community.yml
vars/versions/2019.2-ultimate.yml

2019.2 is now the default version installed.

Updated to IntelliJ version 2019.2

---

README.md
defaults/main.yml
vars/versions/2019.2.1-community.yml
vars/versions/2019.2.1-ultimate.yml

2019.2.1 is now the default version installed.

Updated to IntelliJ version 2019.2.1

---

README.md
defaults/main.yml
vars/versions/2019.2.2-community.yml
vars/versions/2019.2.2-ultimate.yml

2019.2.2 is now the default version installed.

Updated to IntelliJ version 2019.2.2

---

README.md
defaults/main.yml
vars/versions/2019.2.3-community.yml
vars/versions/2019.2.3-ultimate.yml

2019.2.3 is now the default version installed.

Updated to IntelliJ version 2019.2.3

---

README.md
defaults/main.yml
vars/versions/2019.2.4-community.yml
vars/versions/2019.2.4-ultimate.yml

2019.2.4 is now the default version installed.

Updated to IntelliJ version 2019.2.4

---

tasks/install.yml

Optimized installation of dependencies

---

README.md
defaults/main.yml
vars/versions/2019.3-community.yml
vars/versions/2019.3-ultimate.yml

2019.3 is now the default version installed.

Updated to IntelliJ version 2019.3

---

tasks/configure-code-style.yml
tasks/configure-disabled-plugins.yml
tasks/configure-inspection-profiles.yml
tasks/configure-license.yml
tasks/configure-project-defaults.yml
tasks/install-code-styles.yml
tasks/install-inspection-profiles.yml
templates/code.style.schemes.j2
templates/code.style.schemes.xml.j2
templates/disabled_plugins.txt.j2
templates/editor.codeinsight.xml.j2

Added loop variable names

---

tasks/install-code-styles.yml
tasks/install-inspection-profiles.yml

Collect unique list across users.

Optimized download of code styles and inspections

---

tasks/configure-code-style.yml
tasks/configure-disabled-plugins.yml
tasks/configure-inspection-profiles.yml
tasks/configure-jdk-table.yml
tasks/configure-license.yml
tasks/configure-project-defaults.yml
tasks/install-code-styles.yml
tasks/install-inspection-profiles.yml
tasks/install-plugins.yml

Added labels for complex loop items

---

README.md
defaults/main.yml
vars/versions/2019.3.1-community.yml
vars/versions/2019.3.1-ultimate.yml

2019.3.1 is now the default version installed.

Updated to IntelliJ version 2019.3.1

---

library/intellij_install_plugin.py

Support relative location URIs.

Fixed plugin downloads

---

.travis.yml
README.md
library/intellij_configure_jdk.py
library/intellij_install_plugin.py
library/intellij_set_default_inspection_profile.py
library/intellij_set_default_jdk.py
library/intellij_set_default_maven.py
molecule/opensuse/INSTALL.rst
molecule/opensuse/molecule.yml
molecule/opensuse/playbook.yml
molecule/opensuse/tests/test_role.py
tasks/configure-code-style.yml
tasks/configure-disabled-plugins.yml
tasks/configure-inspection-profiles.yml
tasks/configure-jdk-table.yml
tasks/configure-license.yml
tasks/configure-project-defaults.yml
tasks/install-code-styles.yml
tasks/install-inspection-profiles.yml
tasks/install-plugins.yml

For when the group doesn't match the username.
Enhancement resolves: #246

Made group configurable

---

README.md
defaults/main.yml
vars/versions/2019.3.2-community.yml
vars/versions/2019.3.2-ultimate.yml

2019.3.2 is now the default version installed.

Updated to IntelliJ version 2019.3.2

---

README.md
defaults/main.yml
vars/versions/2019.3.3-community.yml
vars/versions/2019.3.3-ultimate.yml

2019.3.3 is now the default version installed.

Updated to IntelliJ version 2019.3.3

---

README.md
defaults/main.yml
vars/versions/2019.3.4-community.yml
vars/versions/2019.3.4-ultimate.yml

2019.3.4 is now the default version installed.

Updated to IntelliJ version 2019.3.4

---

README.md
defaults/main.yml
vars/versions/2020.1-community.yml
vars/versions/2020.1-ultimate.yml

2020.1 is now the default version installed.

Updated to IntelliJ version 2020.1

---

README.md
library/intellij_configure_jdk.py
library/intellij_install_plugin.py
library/intellij_set_default_inspection_profile.py
library/intellij_set_default_jdk.py
library/intellij_set_default_maven.py
molecule/centos/tests/test_role.py
molecule/default/tests/test_role.py
molecule/opensuse/tests/test_role.py
tasks/configure-code-style.yml
tasks/configure-disabled-plugins.yml
tasks/configure-inspection-profiles.yml
tasks/configure-jdk-table.yml
tasks/configure-license.yml
tasks/configure-project-defaults.yml
tasks/install-code-styles.yml
tasks/install-inspection-profiles.yml
tasks/install-plugins.yml
templates/facts.j2
vars/editions/community.yml
vars/editions/ultimate.yml
vars/main.yml

They've changed the directory locations.
Fix: resolves #255

Fixed support for IntelliJ IDEA 2020.1

---

molecule/centos/tests/test_role.py
molecule/default/tests/test_role.py
molecule/opensuse/tests/test_role.py

Fixed plugin install tests

---

README.md
defaults/main.yml
vars/versions/2020.1.1-community.yml
vars/versions/2020.1.1-ultimate.yml

2020.1.1 is now the default version installed.

Updated to IntelliJ version 2020.1.1

---

README.md
defaults/main.yml
vars/versions/2020.1.2-community.yml
vars/versions/2020.1.2-ultimate.yml

2020.1.2 is now the default version installed.

Updated to IntelliJ version 2020.1.2

---

README.md
defaults/main.yml
vars/versions/2020.2.1-community.yml
vars/versions/2020.2.1-ultimate.yml

2020.2.1 is now the default version installed.

Updated to IntelliJ version 2020.2.1

---

README.md
defaults/main.yml
vars/versions/2020.2.2-community.yml
vars/versions/2020.2.2-ultimate.yml

2020.2.2 is now the default version installed.

Updated to IntelliJ version 2020.2.2

---

README.md
defaults/main.yml
vars/versions/2020.2.3-community.yml
vars/versions/2020.2.3-ultimate.yml

2020.2.3 is now the default version installed.

Updated to IntelliJ version 2020.2.3

---

library/intellij_configure_jdk.py
library/intellij_install_plugin.py
library/intellij_set_default_inspection_profile.py
library/intellij_set_default_jdk.py
library/intellij_set_default_maven.py

Reformatted Python code

---

README.md
defaults/main.yml
vars/versions/2020.2.4-community.yml
vars/versions/2020.2.4-ultimate.yml

2020.2.4 is now the default version installed.

Updated to IntelliJ version 2020.2.4

---

README.md
defaults/main.yml
vars/versions/2020.3-community.yml
vars/versions/2020.3-ultimate.yml

2020.3 is now the default version installed.

Updated to IntelliJ version 2020.3

---

README.md
defaults/main.yml
vars/versions/2020.3.1-community.yml
vars/versions/2020.3.1-ultimate.yml

2020.3.1 is now the default version installed.

Updated to IntelliJ version 2020.3.1

---

README.md
defaults/main.yml
vars/versions/2020.3.2-community.yml
vars/versions/2020.3.2-ultimate.yml

2020.3.2 is now the default version installed.

Updated to IntelliJ version 2020.3.2

---

README.md
defaults/main.yml
vars/versions/2020.3.3-community.yml
vars/versions/2020.3.3-ultimate.yml

2020.3.3 is now the default version installed.

Updated to IntelliJ version 2020.3.3

---

README.md
defaults/main.yml
vars/versions/2021.1-community.yml
vars/versions/2021.1-ultimate.yml

2021.1 is now the default version installed.

Updated to IntelliJ version 2021.1

---

README.md
defaults/main.yml
vars/versions/2021.1.1-community.yml
vars/versions/2021.1.1-ultimate.yml

2021.1.1 is now the default version installed.

Updated to IntelliJ version 2021.1.1

---

library/intellij_install_plugin.py

Only affects certain users and certain plugins.

Fixed plugin install Python 3 edge cases

---

README.md
defaults/main.yml
vars/versions/2021.1.3-community.yml
vars/versions/2021.1.3-ultimate.yml

2021.1.3 is now the default version installed.

Updated to IntelliJ version 2021.1.3

---

README.md
defaults/main.yml
library/intellij_install_plugin.py
vars/versions/2021.2-community.yml
vars/versions/2021.2-ultimate.yml

2021.2 is now the default version installed.

Updated to IntelliJ version 2021.2

---

README.md
defaults/main.yml
vars/versions/2021.2.1-community.yml
vars/versions/2021.2.1-ultimate.yml

2021.2.1 is now the default version installed.

Updated to IntelliJ version 2021.2.1

---

README.md
defaults/main.yml
vars/versions/2021.3-community.yml
vars/versions/2021.3-ultimate.yml

2021.3 is now the default version installed.

Updated to IntelliJ version 2021.3

---

README.md
defaults/main.yml
vars/versions/2021.3.1-community.yml
vars/versions/2021.3.1-ultimate.yml

2021.3.1 is now the default version installed.

Updated to IntelliJ version 2021.3.1

---

molecule/minimal/molecule.yml
molecule/opensuse/molecule.yml
molecule/rocky/molecule.yml
molecule/ultimate/molecule.yml

Removed unused test dockerfile config

---

README.md
defaults/main.yml
vars/versions/2021.3.3-community.yml
vars/versions/2021.3.3-ultimate.yml

2021.3.3 is now the default version installed.

Updated to IntelliJ version 2021.3.3

---

README.md
defaults/main.yml
vars/versions/2022.1-community.yml
vars/versions/2022.1-ultimate.yml

2022.1 is now the default version installed.

Updated to IntelliJ version 2022.1

---

README.md

Updated fact examples

---

README.md
defaults/main.yml
vars/versions/2022.2.3-community.yml
vars/versions/2022.2.3-ultimate.yml

I have added thenew sha256 for the version 2022.2.3 from 
- https://download.jetbrains.com/idea/ideaIU-2022.2.3.tar.gz.sha256
- https://download.jetbrains.com/idea/ideaIC-2022.2.3.tar.gz.sha256

Add version 2022.2.3

---

README.md
defaults/main.yml
vars/versions/2022.2.4-community.yml
vars/versions/2022.2.4-ultimate.yml

2022.2.4 is now the default version installed.

Updated to IntelliJ version 2022.2.4

---

README.md
tasks/install-code-styles.yml
tasks/install-inspection-profiles.yml

We want to provide the code styles and inspection profiles in the files folder of the role.
This PR modifies the tasks to copy the files and not downloads them, if something other than a url is provided.

Get xmls from ansible role files directory

---

README.md
defaults/main.yml
vars/versions/2022.3-community.yml
vars/versions/2022.3-ultimate.yml

2022.3 is now the default version installed.

Updated to IntelliJ version 2022.3

---

README.md
defaults/main.yml
molecule/default/converge.yml
molecule/minimal/converge.yml
molecule/ultimate/converge.yml
molecule/ultimate/molecule.yml
tasks/install.yml
vars/main.yml

Added support for inject_facts_as_vars when false

---

README.md
defaults/main.yml
vars/versions/2022.3.1-community.yml
vars/versions/2022.3.1-ultimate.yml

2022.3.1 is now the default version installed.

Updated to IntelliJ version 2022.3.1

---

tasks/install-code-styles.yml
tasks/install-inspection-profiles.yml

Removed double forward slash in paths

---

README.md
library/intellij_configure_jdk.py
library/intellij_install_plugin.py
library/intellij_set_default_inspection_profile.py
library/intellij_set_default_jdk.py
library/intellij_set_default_maven.py
meta/main.yml
molecule/default/converge.yml
molecule/default/molecule.yml
molecule/minimal/converge.yml
molecule/minimal/molecule.yml
molecule/opensuse/converge.yml
molecule/opensuse/molecule.yml
molecule/rocky/converge.yml
molecule/rocky/molecule.yml
molecule/ultimate/converge.yml
molecule/ultimate/molecule.yml
tasks/configure-code-style.yml
tasks/configure-disabled-plugins.yml
tasks/configure-inspection-profiles.yml
tasks/configure-jdk-table.yml
tasks/configure-license.yml
tasks/configure-project-defaults.yml
tasks/configure.yml
tasks/install-code-styles.yml
tasks/install-inspection-profiles.yml
tasks/install-plugins.yml
tasks/install.yml
tasks/main.yml

In preparation for Molecule upgrade.

Fixed Ansible lint warnings

---

README.md
defaults/main.yml
vars/versions/2023.1-community.yml
vars/versions/2023.1-ultimate.yml

2023.1 is now the default version installed.

Updated to IntelliJ version 2023.1

---

.yamllint

Fixed YAML Lint boolean config

---

README.md
defaults/main.yml
vars/versions/2023.1.1-community.yml
vars/versions/2023.1.1-ultimate.yml

2023.1.1 is now the default version installed.

Updated to IntelliJ version 2023.1.1

---

defaults/main.yml
molecule/default/converge.yml
molecule/minimal/converge.yml
molecule/opensuse/converge.yml
molecule/rocky/converge.yml
molecule/ultimate/converge.yml
tasks/configure-code-style.yml
tasks/configure-disabled-plugins.yml
tasks/configure-inspection-profiles.yml
tasks/configure-jdk-table.yml
tasks/configure-license.yml
tasks/configure-project-defaults.yml
tasks/configure.yml
tasks/install-code-styles.yml
tasks/install-inspection-profiles.yml
tasks/install-plugins.yml
tasks/install.yml
tasks/main.yml
vars/editions/community.yml
vars/editions/ultimate.yml
vars/main.yml
vars/os-families/Debian.yml
vars/os-families/RedHat.yml
vars/os-families/Suse.yml
vars/os-families/default.yml

For improved VS Code editing support.

Added Ansible modelines

---

README.md
defaults/main.yml
vars/versions/2023.1.2-community.yml
vars/versions/2023.1.2-ultimate.yml

2023.1.2 is now the default version installed.

Updated to IntelliJ version 2023.1.2

---

README.md
defaults/main.yml
vars/versions/2023.1.3-community.yml
vars/versions/2023.1.3-ultimate.yml

2023.1.3 is now the default version installed.
Enhancement: resolves #357

Updated to IntelliJ version 2023.1.3

---

README.md
defaults/main.yml
vars/versions/2023.1.4-community.yml
vars/versions/2023.1.4-ultimate.yml

2023.1.4 is now the default version installed.

Updated to IntelliJ version 2023.1.4

---

README.md
defaults/main.yml
vars/versions/2023.1.5-community.yml
vars/versions/2023.1.5-ultimate.yml

2023.1.5 is now the default version installed.

Updated to IntelliJ version 2023.1.5

---

README.md
defaults/main.yml
vars/versions/2023.2-community.yml
vars/versions/2023.2-ultimate.yml

2023.2 is now the default version installed.

Updated to IntelliJ version 2023.2

---

.devcontainer/devcontainer.json

Saves a lot of time building it.

Changed to use GantSign devcontainer image

---

molecule/default/tests/test_role.py
molecule/opensuse/tests/test_role.py
molecule/rocky/tests/test_role.py

MavenRunHelper plugin changed their directory name.

Fixed Molecule tests

---

README.md
defaults/main.yml
vars/versions/2023.2.2-community.yml
vars/versions/2023.2.2-ultimate.yml

2023.2.2 is now the default version installed.

Updated to IntelliJ version 2023.2.2

---

README.md
defaults/main.yml
tasks/install.yml

Useful if you want a single user to be able to perform updates.

Added configuration var for install user

---

.github/workflows/ci.yml
README.md
meta/main.yml
molecule/default/molecule.yml
molecule/minimal/molecule.yml

The latest LTS release of Ubuntu.

Increased upper Ubuntu test version to Jammy

---

README.md
defaults/main.yml
vars/versions/2023.2.3-community.yml
vars/versions/2023.2.3-ultimate.yml

2023.2.3 is now the default version installed.

Updated to IntelliJ version 2023.2.3

---

README.md
defaults/main.yml
vars/versions/2023.2.4-community.yml
vars/versions/2023.2.4-ultimate.yml

2023.2.4 is now the default version installed.

Updated to IntelliJ version 2023.2.4

---

README.md

Due to the recent new Galaxy version.

Updated Ansible Galaxy URLs

---

README.md
defaults/main.yml
vars/versions/2023.2.5-community.yml
vars/versions/2023.2.5-ultimate.yml

2023.2.5 is now the default version installed.

Updated to IntelliJ version 2023.2.5

---

README.md
defaults/main.yml
vars/versions/2023.3-community.yml
vars/versions/2023.3-ultimate.yml

2023.3 is now the default version installed.

Updated to IntelliJ version 2023.3

---

README.md
defaults/main.yml
vars/versions/2023.3.1-community.yml
vars/versions/2023.3.1-ultimate.yml

2023.3.1 is now the default version installed.

Updated to IntelliJ version 2023.3.1

---

README.md
defaults/main.yml
vars/versions/2023.3.2-community.yml
vars/versions/2023.3.2-ultimate.yml

2023.3.2 is now the default version installed.

Updated to IntelliJ version 2023.3.2

---

README.md
defaults/main.yml
vars/versions/2023.3.3-community.yml
vars/versions/2023.3.3-ultimate.yml

2023.3.3 is now the default version installed.

Updated to IntelliJ version 2023.3.3

---

README.md
defaults/main.yml
vars/versions/2023.3.4-community.yml
vars/versions/2023.3.4-ultimate.yml

2023.3.4 is now the default version installed.

Updated to IntelliJ version 2023.3.4

---

README.md
defaults/main.yml
vars/versions/2023.3.5-community.yml
vars/versions/2023.3.5-ultimate.yml

2023.3.5 is now the default version installed.

Updated to IntelliJ version 2023.3.5

---

README.md
defaults/main.yml
vars/versions/2023.3.6-community.yml
vars/versions/2023.3.6-ultimate.yml

2023.3.6 is now the default version installed.

Updated to IntelliJ version 2023.3.6

---

tasks/configure.yml
tasks/main.yml

In preparation for Molecule upgrade.

Fixed ansible-lint warnings

---

README.md
defaults/main.yml
vars/versions/2024.1.1-community.yml
vars/versions/2024.1.1-ultimate.yml

2024.1.1 is now the default version installed.

Updated to IntelliJ version 2024.1.1

---

README.md
defaults/main.yml
vars/versions/2024.1.2-community.yml
vars/versions/2024.1.2-ultimate.yml

2024.1.2 is now the default version installed.

Updated to IntelliJ version 2024.1.2

---

README.md
defaults/main.yml
vars/versions/2024.1.3-community.yml
vars/versions/2024.1.3-ultimate.yml

2024.1.3 is now the default version installed.

Updated to IntelliJ version 2024.1.3

---

README.md
defaults/main.yml
vars/versions/2024.1.4-community.yml
vars/versions/2024.1.4-ultimate.yml

2024.1.4 is now the default version installed.

Updated to IntelliJ version 2024.1.4

---

intellij_version_latest.sh
intellij_versions.sh

For querying IntelliJ sha256sums.

Added utility scripts

---

molecule/default/converge.yml
molecule/default/tests/test_role.py
molecule/ultimate/converge.yml

AdoptOpenJDK doesn't provide recent releases.

Switched to Adoptium for JDK

---

README.md
defaults/main.yml
vars/versions/2024.2-community.yml
vars/versions/2024.2-ultimate.yml

2024.2 is now the default version installed.

Updated to IntelliJ version 2024.2

---

.github/dependabot.yml
vars/main.yml

In preparation for upgrade to Ansible Lint 24.10.0.

Fixed lint errors

---

.flake8
library/intellij_configure_jdk.py
library/intellij_install_plugin.py
library/intellij_set_default_inspection_profile.py
library/intellij_set_default_jdk.py
library/intellij_set_default_maven.py
tasks/configure.yml

Dropped support for Python 2 and refactored to use Python 3 features.

Modernized Ansible Module code

---

.github/workflows/ci.yml
README.md
meta/main.yml
molecule/default/molecule.yml
molecule/minimal/molecule.yml

The latest LTS release of Ubuntu.

Increased upper Ubuntu test version to Noble

---

library/intellij_configure_jdk.py
library/intellij_install_plugin.py
library/intellij_set_default_inspection_profile.py
library/intellij_set_default_jdk.py
library/intellij_set_default_maven.py
requirements/ansible-max.in
requirements/ansible-max.txt
requirements/dev.txt

Ensure this role works with Ansible Core 2.17.6.

Increased upper Ansible Core test range to 2.17.6

---

README.md
defaults/main.yml
vars/versions/2024.2.1-community.yml
vars/versions/2024.2.1-ultimate.yml
vars/versions/2024.2.2-community.yml
vars/versions/2024.2.2-ultimate.yml
vars/versions/2024.2.3-community.yml
vars/versions/2024.2.3-ultimate.yml
vars/versions/2024.2.4-community.yml
vars/versions/2024.2.4-ultimate.yml
vars/versions/2024.3-community.yml
vars/versions/2024.3-ultimate.yml

2024.3 is now the default version installed.

Updated to IntelliJ version 2024.3

---

README.md
defaults/main.yml
vars/versions/2024.3.2.1-community.yml
vars/versions/2024.3.2.1-ultimate.yml

2024.3.2.1 is now the default version installed.

Updated to IntelliJ version 2024.3.2.1

---

README.md
defaults/main.yml
vars/versions/2024.3.2.2-community.yml
vars/versions/2024.3.2.2-ultimate.yml
vars/versions/2024.3.3-community.yml
vars/versions/2024.3.3-ultimate.yml
vars/versions/2024.3.4-community.yml
vars/versions/2024.3.4-ultimate.yml
vars/versions/2024.3.4.1-community.yml
vars/versions/2024.3.4.1-ultimate.yml
vars/versions/2024.3.5-community.yml
vars/versions/2024.3.5-ultimate.yml

2024.3.5 is now the default version installed.

Updated to IntelliJ version 2024.3.5
